name: our_mobile_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  rive: ^0.9.1
  flutter_svg: ^1.1.6
  multi_select_flutter: ^4.1.3
  intl: ^0.19.0
  table_calendar: ^3.1.1
  provider: ^6.0.0
  flutter_keyboard_visibility: ^5.0.0
  firebase_core: ^2.3.1
  firebase_auth: ^4.0.2
  google_sign_in: ^6.0.0
  http: ^0.13.3
  shared_preferences: ^2.0.13
  cached_network_image: ^3.2.0
  ticket_widget: ^1.0.2
  barcode_image: ^2.0.3
  get: ^4.6.6
  flutter_rating_bar: ^4.0.1
  image_picker: ^0.8.6
  file_picker: ^8.0.5
  get_storage: ^2.1.1
  qr_code_scanner: ^1.0.0
  email_validator: ^3.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/avaters/
    - assets/Backgrounds/
    - assets/icons/
    - assets/RiveAssets/
    - assets/images/zzz.png
    - assets/images/Z.png
    - assets/images/newZ.png
    - assets/images/splash2.png
    - assets/images/SplashWithoutBg.png
    - assets/images/try.png
    - assets/images/EmailIconPurple.png
    - assets/images/images.jpeg
    - assets/images/picFORcreateEvents/concert.jpg
    - assets/images/picFORcreateEvents/festival.jpg
    - assets/images/picFORcreateEvents/party.jpg
    - assets/images/picFORcreateEvents/wedding.jpg





  fonts:
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700

    - family: Satisfy
      fonts:
        - asset: assets/Fonts/Satisfy-Regular.ttf

    - family: PlayfairDisplay
      fonts:
        - asset: assets/Fonts/PlayfairDisplay-Regular.ttf
