class Localization {
  static const Map<String, String> en = {
    'mostPopular': 'Most Popular',
    'joinAndCreateEvents': 'Join and Create Events',
    'start': 'Start',
    'signup': 'Sign Up',
    'firstName': 'First Name',
    'lastName': 'Last Name',
    'email': 'Email',
    'password': 'Password',
    'address': 'Address',
    'birthdate': 'Birthdate',
    'phoneNumber': 'Phone Number',
    'alreadyHaveAccount': 'Already have an account?',
    'loginHere': 'Login here',
    'login': 'Login',
    'loginWithGoogle': 'Login with Google',
    'noAccount': "You don't have an account?",
    'createOneHere': 'Create one ',
    'findBestEvents': 'Find the best events for you',
    'upcomingEvents': 'Upcoming Events',
    'favoriteEvents': 'Favorite Events',
    'calendarEvents': 'Calendar Events',
    'browse': 'Browse',
    'student': 'Student',
    'home': 'Home',
    'search': 'Search',
    'favorites': 'Favorites',
    'wallet': 'Wallet',
    'searchPage': 'Search Page',
    'whatLookingFor': 'What are you looking for?',
    'category': 'Category',
    'startDateEndDate': 'Start Date and End Date',
    'location': 'Location',
    'minAge': 'Min Age',
    'priceRange': 'Price Range',
    'vipPriceRange': 'VIP Price Range',
    'isFree': 'Is Free',
    'done': 'Done',
    'myWallet': 'My Wallet',
    'sendGift': 'Send Gift',
    'recipient': 'Recipient',
    'selectFollower': 'Select a Follower',
    'amount': 'Amount',
    'send': 'Send',
    'recentTransactions': 'Recent Transactions',
    'withEventasticYouCanMakeYourOwnEvents':'with eventastic you can make your own events with all the details you want and in a simple way',
    'See all the upcoming events':' See all the upcoming events, organize your own events schedule, and pay attention to your rating as an event creator',
    'createEvent':'Create Event',
    'eventName': 'Event Name',
    'Description':'Description',
    'selectStartDate':'Select Start Date',
    'selectEndDate':'Select End Date',
    'selectMinimumAge':'Select Minimum Age',
    'isPaid':'Is Paid',
    'isPrivate':'Is Private',
     'Next':'Next',
    'selectAttendanceType':'Select Attendance Type',
    'Invitation':'Invitation',
    'Ticket':'Ticket',
    'yourEventType':'Your Event Type',
    'cancelCreateEvent':'Cancel Create Event',
    'Select':'Select',
    'Venue':'Venue',
    'cancelEvent':'Cancel Event',
  'Location':'Location',
  'maxCapacity':'Max Capacity',
  'Rating':'Rating',
  'Price':'Price',
  'locationOnMap':'Location On Map',
  'maxCapacityWithChairs':'Max Capacity With Chairs',
  'Chairs':'Chairs',
  'vipChairs':'Vip Chairs',
  'Vip':'Vip',
  'Close':'Close',
  'chooseFurniture':'Choose Furniture',
  'Name':'Name',
  'quantityInWarehouse':'Quantity in warehouse',
  'Cost':'Cost',
  'Choose':'Choose',
  'decorationCategory':'Decoration Category',
  'Available':'Available',
  'Quantity':'Quantity',
  'toOrder,press+':'To order, press +',
  'Order':'Order',
  'soundSelection':'Sound Selection',
  'Genre':'Genre',
  'Reserve':'Reserve',
  'Security':'Security',
  'securitySettings':'Security Settings',
  'costPerGuard':'Cost Per Guard',
  'Food':'Food',
  'selectServingDate':'Select Serving Date',
  'drinkMenu':'Drink Menu',
  'age_required':'age_required',
  'Submit':'Submit',
  'thisEventIsNotPaid':'This event is not paid',
  'Save':'Save',
  'editPrice':'Edit Price',
  'totalCost':'Total Cost',
  'regularTicketPrice':'Regular Ticket Price',
  'vipTicketPrice':'VIP Ticket Price',
    'blockedUsers': 'Blocked Users',
    'unblocked': 'Unblocked',
    'myProfile': 'My Profile',
    'joinDate': 'Join Date',
    'followers': 'Followers',
    'following': 'Following',
    'age': 'Age',
    'points': 'Points',
    'rating': 'Rating',
    'editProfile': 'Edit Profile',
    'myEvents': 'My Events',
    'attendedEvents': 'Attended Events',
    'eventsCreated': 'Events Created',
    'update': 'Update',
    'delete': 'Delete',
    'updatableEvents': 'Updatable Events',
    'eventDetails': 'Event Details',
    'startDate': 'Start Date',
    'endDate': 'End Date',
    'paid': 'Paid',
    'private': 'Private',
    'attendanceType': 'Attendance Type',
    'eventReservations': 'Event Reservations',
    'furnitureReservations': 'Furniture Reservations',
    'musicReservations': 'Music Reservations',
    'securityReservations': 'Security Reservations',
    'foodReservations': 'Food Reservations',
    'drinkReservations': 'Drink Reservations',
    'decorationReservations': 'Decoration Reservations',
    'servingDate': 'Serving Date',
    'noFollowers': 'There are no followers',
    'noUserFollowing': 'No user is following me',
    'quantity': 'Quantity',
    'block': 'Block',
    'unfollow': 'Unfollow',
    'follow': 'Follow',
    'minRating': 'Min Rating',
    // 'email': 'Email',
    // 'phoneNumber': 'Phone Number',
    'name': 'Name',
    'searchUsers': 'Search Users',
    'noUserFound': 'No user found',
    // 'firstName': 'First Name',
    // 'lastName': 'Last Name',
    // 'address': 'Address',
    'birthDate': 'Birth Date',
    'oldPassword': 'Old Password',
    'newPassword': 'New Password',
    'chooseImageSource': 'Choose image source',
    'camera': 'Camera',
    'gallery': 'Gallery',
    'confirmPassword': 'Confirm Password',
    'save': 'Save',
  };

  static const Map<String, String> ar = {
    'mostPopular': 'الأكثر شعبية',
    'joinAndCreateEvents': 'انضم وأنشئ أحداثك',
    'start': 'ابدأ',
    'signup': 'تسجيل',
    'firstName': 'الاسم الأول',
    'lastName': 'الكنية',
    'email': 'البريد الإلكتروني',
    'password': 'كلمة المرور',
    'address': 'العنوان',
    'birthdate': 'تاريخ الميلاد',
    'phoneNumber': 'رقم الهاتف',
    'alreadyHaveAccount': 'هل لديك حساب؟',
    'loginHere': 'تسجيل الدخول هنا',
    'login': 'تسجيل الدخول',
    'loginWithGoogle': 'تسجيل الدخول بواسطة جوجل',
    'noAccount': 'ليس لديك حساب؟',
    'createOneHere': 'أنشئ حساب هنا',
    'findBestEvents': 'ابحث عن أفضل الأحداث لك',
    'upcomingEvents': 'الأحداث القادمة',
    'favoriteEvents': 'الأحداث المفضلة',
    'calendarEvents': 'أحداث التقويم',
    'browse': 'تصفح',
    'student': 'طالب',
    'home': 'الصفحة الرئيسية',
    'search': 'بحث',
    'favorites': 'المفضلة',
    'wallet': 'محفظة',
    'searchPage': 'صفحة البحث',
    'whatLookingFor': 'ماذا تبحث عنه؟',
    'category': 'الفئة',
    'startDateEndDate': 'تاريخ البدء وتاريخ الانتهاء',
    'location': 'الموقع',
    'minAge': 'الحد الأدنى للعمر',
    'priceRange': 'نطاق السعر',
    'vipPriceRange': 'نطاق سعر كبار الشخصيات',
    'isFree': 'مجاني',
    'done': 'تم',
    'myWallet': 'محفظتي',
    'sendGift': 'إرسال هدية',
    'recipient': 'المستلم',
    'selectFollower': 'اختر متابع',
    'amount': 'المبلغ',
    'send': 'إرسال',
    'recentTransactions': 'المعاملات الأخيرة',
    'withEventasticYouCanMakeYourOwnEvents':'مع ايفنتاستيك يمكنك انشاء احداثك الخاصة بكافة التفاصيل التي تريدها و بطريقة بسيطة جدا',
    'See all the upcoming events':'شاهد جميع الاحداث القادمة مع تنظيم جدول احداثك و لا تنسى الانتباه لتقييمك كمنشئ خلال كل ذلك ',
    'createEvent':'إنشاء حدث',
    'eventName':'إسم الحدث',
    'Description': 'الوصف',
    'selectStartDate':'اختر تاريخ البداية',
    'selectEndDate':'اختر تاريخ النهاية ',
    'selectMinimumAge':'إختر أصغر عمر',
    'isPaid':'مدفوع',
    'isPrivate':'خاص',
    'Next':'التالي',
    'selectAttendanceType':'اختر نوع الدعوة',
    'Invitation':'دعوة',
    'Ticket':'تذكرة',
    'yourEventType':'نوع حدثك',
    'cancelCreateEvent':'إلغاء إنشاء حدث',
    'Select':'إختر',
    'Venue':'المكان',
    'cancelEvent':'إلغاء الحدث',
    'Location':'الموقع',
    'maxCapacity':'السعة القصوى',
    'Rating':'التقييم',
    'Price':'السعر',
    'locationOnMap':'الموقع على الخريطة',
    'maxCapacityWithChairs':'السعة القصوى مع الكراسي',
    'Chairs':'الكراسي',
    'vipChairs':'كراسي الأشخاص المهمين',
    'Vip':'درجة اولى',
    'Close':'إغلاق',
    'chooseFurniture':'اختر اثاث',
    'Name':'الاسم',
    'quantityInWarehouse':'الكمية في المستودع',
    'Cost':'التكلفة',
    'Choose':'اختر',
    'decorationCategory':'قسم الديكور',
    'Available':'المتاح',
    'Quantity':'الكمية',
    'toOrder,press+':'للطلب,اضغط+',
    'Order':'اطلب',
    'soundSelection':'اختيار الصوت',
    'Genre':'النمط',
    'Reserve':'احجز',
    'Security':'الأمن',
    'securitySettings':'إعدادات الأمن',
    'costPerGuard':'تكلفة الحارس الواحد',
    'Food':'الطعام',
    'selectServingDate':'اختر تاريخ التقديم',
    'drinkMenu':'قائمة المشروبات',
    'age_required':'العمر المطلوب',
    'Submit':'تسجيل',
    'thisEventIsNotPaid':'هذا الحدث غير مدفوع',
    'Save':'حفظ',
    'editPrice':'تعديل السعر',
    'totalCost':'التكلفة الكلية',
    'regularTicketPrice':'سعر التذكرة العادية',
    'vipTicketPrice':'سعر تذكرة الدرجة الاولى',
    'blockedUsers': 'المستخدمون المحظورون',
    'unblocked': 'غير محظور',
    'myProfile': 'ملفي الشخصي',
    'joinDate': 'تاريخ الانضمام',
    'followers': 'المتابعون',
    'following': 'يتابع',
    'age': 'العمر',
    'points': 'النقاط',
    'rating': 'التقييم',
    'editProfile': 'تعديل الملف الشخصي',
    'myEvents': 'فعالياتي',
    'attendedEvents': 'الفعاليات التي حضرتها',
    'eventsCreated': 'الفعاليات التي أنشأتها',
    'update': 'تحديث',
    'delete': 'حذف',
    'updatableEvents': 'الفعاليات القابلة للتحديث',
    'eventDetails': 'تفاصيل الفعالية',
    'startDate': 'تاريخ البدء',
    'endDate': 'تاريخ الانتهاء',
    'paid': 'مدفوع',
    'private': 'خاص',
    'attendanceType': 'نوع الحضور',
    'eventReservations': 'حجوزات الفعالية',
    'furnitureReservations': 'حجوزات الأثاث',
    'musicReservations': 'حجوزات الموسيقى',
    'securityReservations': 'حجوزات الأمن',
    'foodReservations': 'حجوزات الطعام',
    'drinkReservations': 'حجوزات المشروبات',
    'decorationReservations': 'حجوزات الزينة',
    'servingDate': 'تاريخ التقديم',
    'noFollowers': 'لا يوجد متابعون',
    'noUserFollowing': 'لا يوجد مستخدم يتابعني',
    'quantity': 'الكمية',
    'block': 'حظر',
    'unfollow': 'إلغاء المتابعة',
    'follow': 'متابعة',
    'minRating': 'أدنى تقييم',
    // 'email': 'البريد الإلكتروني',
    // 'phoneNumber': 'رقم الهاتف',
    'name': 'الاسم',
    'searchUsers': 'البحث عن مستخدمين',
    'noUserFound': 'لم يتم العثور على مستخدم',
    // 'firstName': 'الاسم الأول',
    // 'lastName': 'الاسم الأخير',
    // 'address': 'العنوان',
    'birthDate': 'تاريخ الميلاد',
    'oldPassword': 'كلمة المرور القديمة',
    'newPassword': 'كلمة المرور الجديدة',
    'chooseImageSource': 'اختر مصدر الصورة',
    'camera': 'الكاميرا',
    'gallery': 'المعرض',
    'confirmPassword': 'تأكيد كلمة المرور',
    'save': 'حفظ',
  };
}
