// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAMa6b9q5FUeslYfQg-S5qvQhmINda3cI',
    appId: '1:784942274502:web:69adaab159d62f625984c7',
    messagingSenderId: '784942274502',
    projectId: 'authev-13ed6',
    authDomain: 'authev-13ed6.firebaseapp.com',
    storageBucket: 'authev-13ed6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtNYXbwiM5XSW96I80PKiECMDbWv1DpmY',
    appId: '1:784942274502:android:6ac28a2a862e17bb5984c7',
    messagingSenderId: '784942274502',
    projectId: 'authev-13ed6',
    storageBucket: 'authev-13ed6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlLXiZ-M5TZ49SgtE_8Rqvg6Q-s5ydE0Q',
    appId: '1:784942274502:ios:f02f4317ec97e2bf5984c7',
    messagingSenderId: '784942274502',
    projectId: 'authev-13ed6',
    storageBucket: 'authev-13ed6.appspot.com',
    androidClientId: '784942274502-0k50o3b5a3fejge9ig2425tb3t4nalst.apps.googleusercontent.com',
    iosClientId: '784942274502-k9udrh7h79alsas651fmm2ijohfarg8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlLXiZ-M5TZ49SgtE_8Rqvg6Q-s5ydE0Q',
    appId: '1:784942274502:ios:f02f4317ec97e2bf5984c7',
    messagingSenderId: '784942274502',
    projectId: 'authev-13ed6',
    storageBucket: 'authev-13ed6.appspot.com',
    androidClientId: '784942274502-0k50o3b5a3fejge9ig2425tb3t4nalst.apps.googleusercontent.com',
    iosClientId: '784942274502-k9udrh7h79alsas651fmm2ijohfarg8o.apps.googleusercontent.com',
    iosBundleId: 'com.example.ourMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAMa6b9q5FUeslYfQg-S5qvQhmINda3cI',
    appId: '1:784942274502:web:de5eaf27dec1c93c5984c7',
    messagingSenderId: '784942274502',
    projectId: 'authev-13ed6',
    authDomain: 'authev-13ed6.firebaseapp.com',
    storageBucket: 'authev-13ed6.appspot.com',
  );

}